# Generated by Django 4.2 on 2025-03-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='people',
        ),
    ]
